/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type ExhibitionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'exhibition'
}

export type CvEntry = {
  _id: string
  _type: 'cvEntry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title: string
  year: number
  category:
    | 'exhibition'
    | 'education'
    | 'award'
    | 'residency'
    | 'publication'
    | 'performance'
    | 'screening'
    | 'commission'
    | 'lecture'
    | 'other'
  role?: string
  institution?: string
  location?: string
  description?: string
  internalRef?: ExhibitionReference
}

export type WorkReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'work'
}

export type Exhibition = {
  _id: string
  _type: 'exhibition'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title: string
  slug: Slug
  year?: number
  venue?: string
  location?: string
  startDate?: string
  endDate?: string
  exhibitionType?: 'solo' | 'group' | 'duo' | 'institutional'
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  relatedWorks?: Array<
    {
      _key: string
    } & WorkReference
  >
  installationImages?: Array<
    {
      _key: string
    } & MediaItem
  >
  externalDocumentationLink?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Ephemera = {
  _id: string
  _type: 'ephemera'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title: string
  slug: Slug
  year?: number
  category?: 'research' | 'sketch' | 'reference' | 'documentation' | 'correspondence' | 'other'
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  images?: Array<
    {
      _key: string
    } & MediaItem
  >
  media?: Array<
    {
      _key: string
    } & MediaItem
  >
  relatedWork?: Array<
    {
      _key: string
    } & WorkReference
  >
  relatedExhibitions?: Array<
    {
      _key: string
    } & ExhibitionReference
  >
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type EphemeraReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'ephemera'
}

export type Work = {
  _id: string
  _type: 'work'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title: string
  slug: Slug
  year: number
  medium?: string
  dimensions?: string
  duration?: string
  videoUrl?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  artistStatement?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  gallery?: Array<
    {
      _key: string
    } & MediaItem
  >
  isFeature?: boolean
  relatedEphemera?: Array<
    {
      _key: string
    } & EphemeraReference
  >
  tags?: Array<string>
  collaborators?: Array<string>
  commissionedBy?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type MediaItem = {
  _type: 'mediaItem'
  mediaType?: 'image' | 'video'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  videoSource?: 'url' | 'file' | 'vimeo'
  videoUrl?: string
  videoFile?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
  vimeo?: Vimeo
  isAudiencePhoto?: boolean
  caption?: string
  credit?: string
}

export type VimeoVideoReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'vimeoVideo'
}

export type Vimeo = {
  _type: 'vimeo'
  asset?: VimeoVideoReference
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type VimeoVideo = {
  _id: string
  _type: 'vimeoVideo'
  _createdAt: string
  _updatedAt: string
  _rev: string
  vimeoId?: string
  name?: string
  duration?: number
  width?: number
  height?: number
  privacy?: string
  lastSynced?: string
  pictures?: {
    sizes?: Array<{
      width?: number
      height?: number
      link?: string
      _key: string
    }>
  }
  files?: Array<{
    quality?: string
    type?: string
    width?: number
    height?: number
    link?: string
    size?: number
    _key: string
  }>
  play?: {
    progressive?: Array<{
      type?: string
      rendition?: string
      width?: number
      height?: number
      link?: string
      _key: string
    }>
    dash?: {
      link?: string
    }
    hls?: {
      link?: string
    }
  }
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | ExhibitionReference
  | CvEntry
  | WorkReference
  | Exhibition
  | Slug
  | Ephemera
  | SanityImageAssetReference
  | EphemeraReference
  | Work
  | SanityImageCrop
  | SanityImageHotspot
  | SanityFileAssetReference
  | MediaItem
  | VimeoVideoReference
  | Vimeo
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | VimeoVideo
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: streamQuery
// Query: *[_type in ["work", "ephemera"] && defined(slug.current)]  | order(orderRank asc) {    _id,    _type,    title,    "slug": slug.current,    year,    coverImage { ..., asset-> },    "firstImage": images[0] { ..., asset-> }  }
export type StreamQueryResult = Array<
  | {
      _id: string
      _type: 'ephemera'
      title: string
      slug: string
      year: number | null
      coverImage: null
      firstImage: {
        _key: string
        _type: 'mediaItem'
        mediaType?: 'image' | 'video'
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        videoSource?: 'file' | 'url' | 'vimeo'
        videoUrl?: string
        videoFile?: {
          asset?: SanityFileAssetReference
          media?: unknown
          _type: 'file'
        }
        vimeo?: Vimeo
        isAudiencePhoto?: boolean
        caption?: string
        credit?: string
        asset: null
      } | null
    }
  | {
      _id: string
      _type: 'work'
      title: string
      slug: string
      year: number
      coverImage: {
        asset: {
          _id: string
          _type: 'sanity.imageAsset'
          _createdAt: string
          _updatedAt: string
          _rev: string
          originalFilename?: string
          label?: string
          title?: string
          description?: string
          altText?: string
          sha1hash: string
          extension: string
          mimeType: string
          size: number
          assetId: string
          uploadId?: string
          path: string
          url: string
          metadata?: SanityImageMetadata
          source?: SanityAssetSourceData
        } | null
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      } | null
      firstImage: null
    }
>

// Source: sanity/lib/queries.ts
// Variable: archiveQuery
// Query: *[_type == "work" && defined(slug.current) && year < 2015]  | order(orderRank asc) {      _id,  _type,  title,  "slug": slug.current,  year,  medium,  coverImage { ..., asset-> }  }
export type ArchiveQueryResult = Array<{
  _id: string
  _type: 'work'
  title: string
  slug: string
  year: number
  medium: string | null
  coverImage: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: workQuery
// Query: *[_type == "work" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    year,    medium,    dimensions,    description,    coverImage { ..., asset-> },    gallery[] {   mediaType,  videoSource,  image { ..., asset-> },  videoUrl,  videoFile { asset-> },  vimeo {    asset-> {      vimeoId,      name,      duration,      width,      height,      privacy,      "thumbnail": pictures.sizes[0].link,      files,      play    }  },  isAudiencePhoto,  caption,  credit },    relatedEphemera[]-> {      _id,      title,      "slug": slug.current,      category,      "firstImage": images[0] { ..., asset-> }    },    tags,    "exhibitions": *[_type == "exhibition" && references(^._id)] {      _id,      title,      "slug": slug.current,      year,      venue,      location    }  }
export type WorkQueryResult = {
  _id: string
  title: string
  slug: string
  year: number
  medium: string | null
  dimensions: string | null
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  coverImage: {
    asset: {
      _id: string
      _type: 'sanity.imageAsset'
      _createdAt: string
      _updatedAt: string
      _rev: string
      originalFilename?: string
      label?: string
      title?: string
      description?: string
      altText?: string
      sha1hash: string
      extension: string
      mimeType: string
      size: number
      assetId: string
      uploadId?: string
      path: string
      url: string
      metadata?: SanityImageMetadata
      source?: SanityAssetSourceData
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  gallery: Array<{
    mediaType: 'image' | 'video' | null
    videoSource: 'file' | 'url' | 'vimeo' | null
    image: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash: string
        extension: string
        mimeType: string
        size: number
        assetId: string
        uploadId?: string
        path: string
        url: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    videoUrl: string | null
    videoFile: {
      asset: {
        _id: string
        _type: 'sanity.fileAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash: string
        extension: string
        mimeType: string
        size: number
        assetId: string
        uploadId?: string
        path: string
        url: string
        source?: SanityAssetSourceData
      } | null
    } | null
    vimeo: {
      asset: {
        vimeoId: string | null
        name: string | null
        duration: number | null
        width: number | null
        height: number | null
        privacy: string | null
        thumbnail: string | null
        files: Array<{
          quality?: string
          type?: string
          width?: number
          height?: number
          link?: string
          size?: number
          _key: string
        }> | null
        play: {
          progressive?: Array<{
            type?: string
            rendition?: string
            width?: number
            height?: number
            link?: string
            _key: string
          }>
          dash?: {
            link?: string
          }
          hls?: {
            link?: string
          }
        } | null
      } | null
    } | null
    isAudiencePhoto: boolean | null
    caption: string | null
    credit: string | null
  }> | null
  relatedEphemera: Array<{
    _id: string
    title: string
    slug: string
    category:
      | 'correspondence'
      | 'documentation'
      | 'other'
      | 'reference'
      | 'research'
      | 'sketch'
      | null
    firstImage: {
      _key: string
      _type: 'mediaItem'
      mediaType?: 'image' | 'video'
      image?: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      videoSource?: 'file' | 'url' | 'vimeo'
      videoUrl?: string
      videoFile?: {
        asset?: SanityFileAssetReference
        media?: unknown
        _type: 'file'
      }
      vimeo?: Vimeo
      isAudiencePhoto?: boolean
      caption?: string
      credit?: string
      asset: null
    } | null
  }> | null
  tags: Array<string> | null
  exhibitions: Array<{
    _id: string
    title: string
    slug: string
    year: number | null
    venue: string | null
    location: string | null
  }>
} | null

// Source: sanity/lib/queries.ts
// Variable: workSlugQuery
// Query: *[_type == "work" && defined(slug.current)] { "slug": slug.current }
export type WorkSlugQueryResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: exhibitionQuery
// Query: *[_type == "exhibition" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    year,    venue,    location,    startDate,    endDate,    exhibitionType,    description,    externalDocumentationLink,    relatedWorks[]-> {        _id,  _type,  title,  "slug": slug.current,  year,  medium,  coverImage { ..., asset-> }    },    installationImages[] {   mediaType,  videoSource,  image { ..., asset-> },  videoUrl,  videoFile { asset-> },  vimeo {    asset-> {      vimeoId,      name,      duration,      width,      height,      privacy,      "thumbnail": pictures.sizes[0].link,      files,      play    }  },  isAudiencePhoto,  caption,  credit },    "relatedEphemera": *[_type == "ephemera" && references(^._id)] {      _id,      title,      "slug": slug.current,      category,      year    }  }
export type ExhibitionQueryResult = {
  _id: string
  title: string
  slug: string
  year: number | null
  venue: string | null
  location: string | null
  startDate: string | null
  endDate: string | null
  exhibitionType: 'duo' | 'group' | 'institutional' | 'solo' | null
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  externalDocumentationLink: string | null
  relatedWorks: Array<{
    _id: string
    _type: 'work'
    title: string
    slug: string
    year: number
    medium: string | null
    coverImage: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash: string
        extension: string
        mimeType: string
        size: number
        assetId: string
        uploadId?: string
        path: string
        url: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  }> | null
  installationImages: Array<{
    mediaType: 'image' | 'video' | null
    videoSource: 'file' | 'url' | 'vimeo' | null
    image: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash: string
        extension: string
        mimeType: string
        size: number
        assetId: string
        uploadId?: string
        path: string
        url: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    videoUrl: string | null
    videoFile: {
      asset: {
        _id: string
        _type: 'sanity.fileAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash: string
        extension: string
        mimeType: string
        size: number
        assetId: string
        uploadId?: string
        path: string
        url: string
        source?: SanityAssetSourceData
      } | null
    } | null
    vimeo: {
      asset: {
        vimeoId: string | null
        name: string | null
        duration: number | null
        width: number | null
        height: number | null
        privacy: string | null
        thumbnail: string | null
        files: Array<{
          quality?: string
          type?: string
          width?: number
          height?: number
          link?: string
          size?: number
          _key: string
        }> | null
        play: {
          progressive?: Array<{
            type?: string
            rendition?: string
            width?: number
            height?: number
            link?: string
            _key: string
          }>
          dash?: {
            link?: string
          }
          hls?: {
            link?: string
          }
        } | null
      } | null
    } | null
    isAudiencePhoto: boolean | null
    caption: string | null
    credit: string | null
  }> | null
  relatedEphemera: Array<{
    _id: string
    title: string
    slug: string
    category:
      | 'correspondence'
      | 'documentation'
      | 'other'
      | 'reference'
      | 'research'
      | 'sketch'
      | null
    year: number | null
  }>
} | null

// Source: sanity/lib/queries.ts
// Variable: exhibitionSlugQuery
// Query: *[_type == "exhibition" && defined(slug.current)] { "slug": slug.current }
export type ExhibitionSlugQueryResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: ephemeraQuery
// Query: *[_type == "ephemera" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    year,    category,    description,    media[] {   mediaType,  videoSource,  image { ..., asset-> },  videoUrl,  videoFile { asset-> },  vimeo {    asset-> {      vimeoId,      name,      duration,      width,      height,      privacy,      "thumbnail": pictures.sizes[0].link,      files,      play    }  },  isAudiencePhoto,  caption,  credit },    relatedWork[]-> {      _id,      title,      "slug": slug.current,      year,      medium    },    relatedExhibitions[]-> {      _id,      title,      "slug": slug.current,      year,      venue,      location    }  }
export type EphemeraQueryResult = {
  _id: string
  title: string
  slug: string
  year: number | null
  category:
    | 'correspondence'
    | 'documentation'
    | 'other'
    | 'reference'
    | 'research'
    | 'sketch'
    | null
  description: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  media: Array<{
    mediaType: 'image' | 'video' | null
    videoSource: 'file' | 'url' | 'vimeo' | null
    image: {
      asset: {
        _id: string
        _type: 'sanity.imageAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash: string
        extension: string
        mimeType: string
        size: number
        assetId: string
        uploadId?: string
        path: string
        url: string
        metadata?: SanityImageMetadata
        source?: SanityAssetSourceData
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    videoUrl: string | null
    videoFile: {
      asset: {
        _id: string
        _type: 'sanity.fileAsset'
        _createdAt: string
        _updatedAt: string
        _rev: string
        originalFilename?: string
        label?: string
        title?: string
        description?: string
        altText?: string
        sha1hash: string
        extension: string
        mimeType: string
        size: number
        assetId: string
        uploadId?: string
        path: string
        url: string
        source?: SanityAssetSourceData
      } | null
    } | null
    vimeo: {
      asset: {
        vimeoId: string | null
        name: string | null
        duration: number | null
        width: number | null
        height: number | null
        privacy: string | null
        thumbnail: string | null
        files: Array<{
          quality?: string
          type?: string
          width?: number
          height?: number
          link?: string
          size?: number
          _key: string
        }> | null
        play: {
          progressive?: Array<{
            type?: string
            rendition?: string
            width?: number
            height?: number
            link?: string
            _key: string
          }>
          dash?: {
            link?: string
          }
          hls?: {
            link?: string
          }
        } | null
      } | null
    } | null
    isAudiencePhoto: boolean | null
    caption: string | null
    credit: string | null
  }> | null
  relatedWork: Array<{
    _id: string
    title: string
    slug: string
    year: number
    medium: string | null
  }> | null
  relatedExhibitions: Array<{
    _id: string
    title: string
    slug: string
    year: number | null
    venue: string | null
    location: string | null
  }> | null
} | null

// Source: sanity/lib/queries.ts
// Variable: ephemeraSlugQuery
// Query: *[_type == "ephemera" && defined(slug.current)] { "slug": slug.current }
export type EphemeraSlugQueryResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: cvQuery
// Query: *[_type == "cvEntry"] | order(orderRank asc) {    _id,    title,    year,    category,    role,    institution,    location,    description,    internalRef-> {      _id,      title,      "slug": slug.current    }  }
export type CvQueryResult = Array<{
  _id: string
  title: string
  year: number
  category:
    | 'award'
    | 'commission'
    | 'education'
    | 'exhibition'
    | 'lecture'
    | 'other'
    | 'performance'
    | 'publication'
    | 'residency'
    | 'screening'
  role: string | null
  institution: string | null
  location: string | null
  description: string | null
  internalRef: {
    _id: string
    title: string
    slug: string
  } | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[_type in ["work", "ephemera"] && defined(slug.current)]\n  | order(orderRank asc) {\n    _id,\n    _type,\n    title,\n    "slug": slug.current,\n    year,\n    coverImage { ..., asset-> },\n    "firstImage": images[0] { ..., asset-> }\n  }\n': StreamQueryResult
    '\n  *[_type == "work" && defined(slug.current) && year < 2015]\n  | order(orderRank asc) {\n    \n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  year,\n  medium,\n  coverImage { ..., asset-> }\n\n  }\n': ArchiveQueryResult
    '\n  *[_type == "work" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    year,\n    medium,\n    dimensions,\n    description,\n    coverImage { ..., asset-> },\n    gallery[] { \n  mediaType,\n  videoSource,\n  image { ..., asset-> },\n  videoUrl,\n  videoFile { asset-> },\n  vimeo {\n    asset-> {\n      vimeoId,\n      name,\n      duration,\n      width,\n      height,\n      privacy,\n      "thumbnail": pictures.sizes[0].link,\n      files,\n      play\n    }\n  },\n  isAudiencePhoto,\n  caption,\n  credit\n },\n    relatedEphemera[]-> {\n      _id,\n      title,\n      "slug": slug.current,\n      category,\n      "firstImage": images[0] { ..., asset-> }\n    },\n    tags,\n    "exhibitions": *[_type == "exhibition" && references(^._id)] {\n      _id,\n      title,\n      "slug": slug.current,\n      year,\n      venue,\n      location\n    }\n  }\n': WorkQueryResult
    '\n  *[_type == "work" && defined(slug.current)] { "slug": slug.current }\n': WorkSlugQueryResult
    '\n  *[_type == "exhibition" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    year,\n    venue,\n    location,\n    startDate,\n    endDate,\n    exhibitionType,\n    description,\n    externalDocumentationLink,\n    relatedWorks[]-> {\n      \n  _id,\n  _type,\n  title,\n  "slug": slug.current,\n  year,\n  medium,\n  coverImage { ..., asset-> }\n\n    },\n    installationImages[] { \n  mediaType,\n  videoSource,\n  image { ..., asset-> },\n  videoUrl,\n  videoFile { asset-> },\n  vimeo {\n    asset-> {\n      vimeoId,\n      name,\n      duration,\n      width,\n      height,\n      privacy,\n      "thumbnail": pictures.sizes[0].link,\n      files,\n      play\n    }\n  },\n  isAudiencePhoto,\n  caption,\n  credit\n },\n    "relatedEphemera": *[_type == "ephemera" && references(^._id)] {\n      _id,\n      title,\n      "slug": slug.current,\n      category,\n      year\n    }\n  }\n': ExhibitionQueryResult
    '\n  *[_type == "exhibition" && defined(slug.current)] { "slug": slug.current }\n': ExhibitionSlugQueryResult
    '\n  *[_type == "ephemera" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    year,\n    category,\n    description,\n    media[] { \n  mediaType,\n  videoSource,\n  image { ..., asset-> },\n  videoUrl,\n  videoFile { asset-> },\n  vimeo {\n    asset-> {\n      vimeoId,\n      name,\n      duration,\n      width,\n      height,\n      privacy,\n      "thumbnail": pictures.sizes[0].link,\n      files,\n      play\n    }\n  },\n  isAudiencePhoto,\n  caption,\n  credit\n },\n    relatedWork[]-> {\n      _id,\n      title,\n      "slug": slug.current,\n      year,\n      medium\n    },\n    relatedExhibitions[]-> {\n      _id,\n      title,\n      "slug": slug.current,\n      year,\n      venue,\n      location\n    }\n  }\n': EphemeraQueryResult
    '\n  *[_type == "ephemera" && defined(slug.current)] { "slug": slug.current }\n': EphemeraSlugQueryResult
    '\n  *[_type == "cvEntry"] | order(orderRank asc) {\n    _id,\n    title,\n    year,\n    category,\n    role,\n    institution,\n    location,\n    description,\n    internalRef-> {\n      _id,\n      title,\n      "slug": slug.current\n    }\n  }\n': CvQueryResult
  }
}
