/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type ExhibitionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'exhibition'
}

export type CvEntry = {
  _id: string
  _type: 'cvEntry'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  year: number
  category:
    | 'exhibition'
    | 'education'
    | 'award'
    | 'residency'
    | 'publication'
    | 'performance'
    | 'screening'
    | 'commission'
    | 'lecture'
    | 'other'
  role?: string
  institution?: string
  location?: string
  description?: string
  internalRef?: ExhibitionReference
}

export type WorkReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'work'
}

export type Ephemera = {
  _id: string
  _type: 'ephemera'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title: string
  slug: Slug
  year?: number
  category?: 'research' | 'sketch' | 'reference' | 'documentation' | 'correspondence' | 'other'
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  images?: Array<
    | ({
        _key: string
      } & MediaImage)
    | ({
        _key: string
      } & MediaVideoFile)
    | ({
        _key: string
      } & MediaVideoLink)
  >
  relatedWork?: Array<
    {
      _key: string
    } & WorkReference
  >
  relatedExhibitions?: Array<
    {
      _key: string
    } & ExhibitionReference
  >
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type EphemeraReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'ephemera'
}

export type Work = {
  _id: string
  _type: 'work'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title: string
  slug: Slug
  year: number
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  gallery?: Array<
    | ({
        _key: string
      } & MediaImage)
    | ({
        _key: string
      } & MediaVideoFile)
    | ({
        _key: string
      } & MediaVideoLink)
  >
  exhibition?: ExhibitionReference
  carouselImage?: MediaImage
  medium?: string
  dimensions?: string
  duration?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  artistStatement?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  relatedEphemera?: Array<
    {
      _key: string
    } & EphemeraReference
  >
  tags?: Array<string>
  collaborators?: Array<string>
  commissionedBy?: string
}

export type MediaImage = {
  _type: 'mediaImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  isAudiencePhoto?: boolean
  caption?: string
  credit?: string
}

export type Exhibition = {
  _id: string
  _type: 'exhibition'
  _createdAt: string
  _updatedAt: string
  _rev: string
  orderRank?: string
  title: string
  slug: Slug
  hidePublicPage?: boolean
  carouselImage?: MediaImage
  year?: number
  installationImages?: Array<
    | ({
        _key: string
      } & MediaImage)
    | ({
        _key: string
      } & MediaVideoFile)
    | ({
        _key: string
      } & MediaVideoLink)
  >
  venue?: string
  location?: string
  startDate?: string
  endDate?: string
  exhibitionType?: 'solo' | 'group' | 'duo' | 'institutional'
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  relatedWorks?: Array<
    {
      _key: string
    } & WorkReference
  >
  externalDocumentationLink?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type MediaVideoLink = {
  _type: 'mediaVideoLink'
  provider: 'vimeo' | 'youtube'
  vimeo?: Vimeo
  youtube?: YoutubeVideo
  caption?: string
  credit?: string
}

export type YoutubeVideo = {
  _type: 'youtubeVideo'
  id: string
  title?: string
  description?: string
  publishedAt?: string
  thumbnails?: Array<string>
}

export type VimeoVideoReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'vimeoVideo'
}

export type Vimeo = {
  _type: 'vimeo'
  asset?: VimeoVideoReference
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type MediaVideoFile = {
  _type: 'mediaVideoFile'
  asset?: SanityFileAssetReference
  media?: unknown
  caption?: string
  credit?: string
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  homepageCarousel?: Array<
    | ({
        _key: string
      } & WorkReference)
    | ({
        _key: string
      } & ExhibitionReference)
  >
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type VimeoVideo = {
  _id: string
  _type: 'vimeoVideo'
  _createdAt: string
  _updatedAt: string
  _rev: string
  vimeoId?: string
  name?: string
  duration?: number
  width?: number
  height?: number
  privacy?: string
  lastSynced?: string
  pictures?: {
    sizes?: Array<{
      width?: number
      height?: number
      link?: string
      _key: string
    }>
  }
  files?: Array<{
    quality?: string
    type?: string
    width?: number
    height?: number
    link?: string
    size?: number
    _key: string
  }>
  play?: {
    progressive?: Array<{
      type?: string
      rendition?: string
      width?: number
      height?: number
      link?: string
      _key: string
    }>
    dash?: {
      link?: string
    }
    hls?: {
      link?: string
    }
  }
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | ExhibitionReference
  | CvEntry
  | WorkReference
  | Ephemera
  | Slug
  | SanityImageAssetReference
  | EphemeraReference
  | Work
  | MediaImage
  | Exhibition
  | SanityImageCrop
  | SanityImageHotspot
  | MediaVideoLink
  | YoutubeVideo
  | VimeoVideoReference
  | Vimeo
  | SanityFileAssetReference
  | MediaVideoFile
  | SiteSettings
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | VimeoVideo
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
